name: Status Check

on:
  push:
    branches: [ main, develop, "feat/*" ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quick-check:
    runs-on: ubuntu-latest
    timeout-minutes: 2  # Limit để tiết kiệm phút

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Check package.json
        run: |
          if [ -f "package.json" ]; then
            echo "✅ package.json exists"
            node -e "JSON.parse(require('fs').readFileSync('package.json', 'utf8'))"
            echo "✅ package.json is valid JSON"
          else
            echo "❌ package.json not found"
            exit 1
          fi

      - name: Install dependencies (fast)
        run: npm ci --only=production

      - name: Syntax check
        run: |
          if [ -f "app.js" ]; then
            node -c app.js
            echo "✅ app.js syntax OK"
          else
            echo "❌ app.js not found"
            exit 1
          fi

      - name: Environment check
        run: |
          echo "✅ Node version: $(node --version)"
          echo "✅ NPM version: $(npm --version)"
          echo "✅ Basic checks passed"